# Generated by Django 5.2.1 on 2025-09-08 03:50

from django.db import migrations

def create_admin_user(apps, schema_editor):
    User = apps.get_model("core", "User")  
    if not User.objects.filter(username="admin").exists():
        User.objects.create_superuser(
            username="admin",
            email="admin1@gmail.com",
            password="Kenya@2030" 
        )

def delete_admin_user(apps, schema_editor):
    User = apps.get_model("core", "User")
    User.objects.filter(username="admin").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.RunPython(create_admin_user, reverse_code=delete_admin_user),
    ]
