# Generated by Django 5.2.1 on 2025-09-07 17:15

from django.db import migrations

def seed_senators(apps, schema_editor):
    Leader = apps.get_model("kyl", "Leader")
    County = apps.get_model("kyl", "County")
    Position = apps.get_model("kyl", "Position")

    # Ensure "Senator" position exists
    senator_position, _ = Position.objects.get_or_create(name="Senator")

    senators = [
        {"county": "Mombasa", "name": "Mohamed Faki Mwinyihaji", "party": "ODM"},
        {"county": "Kwale", "name": "Issa Boy Juma", "party": "ODM"},
        {"county": "Kilifi", "name": "Stewart Madzayo", "party": "ODM"},
        {"county": "Tana River", "name": "Danson Mungatana", "party": "UDA"},
        {"county": "Lamu", "name": "Joseph Githuku", "party": "Jubilee"},
        {"county": "Taita-Taveta", "name": "Johnes Mwaruma", "party": "ODM"},
        {"county": "Garissa", "name": "Abdulkadir Haji", "party": "Jubilee"},
        {"county": "Wajir", "name": "Abbas Sheikh", "party": "UDM"},
        {"county": "Mandera", "name": "Ali Roba", "party": "UDM"},
        {"county": "Marsabit", "name": "Mohamed Chute", "party": "UDA"},
        {"county": "Isiolo", "name": "Fatuma Adan Dulo", "party": "Jubilee"},
        {"county": "Meru", "name": "Kathuri Murungi", "party": "UDA"},
        {"county": "Tharaka-Nithi", "name": "Mwenda Gataya", "party": "UDA"},
        {"county": "Embu", "name": "Alexander Mundigi", "party": "DP"},
        {"county": "Kitui", "name": "Enock Wambua", "party": "Wiper"},
        {"county": "Machakos", "name": "Agnes Kavindu", "party": "Wiper"},
        {"county": "Makueni", "name": "Daniel Maanzo", "party": "Wiper"},
        {"county": "Nyandarua", "name": "John Methu", "party": "UDA"},
        {"county": "Nyeri", "name": "Wahome Wamatinga", "party": "UDA"},
        {"county": "Kirinyaga", "name": "Kamau Murango", "party": "UDA"},
        {"county": "Murang’a", "name": "Joe Nyutu", "party": "UDA"},
        {"county": "Kiambu", "name": "Karungo Thang’wa", "party": "UDA"},
        {"county": "Turkana", "name": "James Lomenen Ekomwa", "party": "Upya Party"},
        {"county": "West Pokot", "name": "Julius Murgor", "party": "UDA"},
        {"county": "Samburu", "name": "Steve Lelegwe", "party": "UDA"},
        {"county": "Trans-Nzoia", "name": "Allan Chesang", "party": "UDA"},
        {"county": "Uasin Gishu", "name": "Jackson Mandago", "party": "UDA"},
        {"county": "Elgeyo-Marakwet", "name": "Kipchumba Murkomen", "party": "UDA"},
        {"county": "Nandi", "name": "Samson Cherargei", "party": "UDA"},
        {"county": "Baringo", "name": "William Cheptumo", "party": "UDA"},
        {"county": "Laikipia", "name": "John Kinyua", "party": "UDA"},
        {"county": "Nakuru", "name": "Tabitha Karanja", "party": "UDA"},
        {"county": "Narok", "name": "Ledama Olekina", "party": "ODM"},
        {"county": "Kajiado", "name": "Samuel Seki", "party": "UDA"},
        {"county": "Kericho", "name": "Aaron Kipkirui Cheruiyot", "party": "UDA"},
        {"county": "Bomet", "name": "Hillary Sigei", "party": "UDA"},
        {"county": "Kakamega", "name": "Boni Khalwale", "party": "UDA"},
        {"county": "Vihiga", "name": "Godfrey Osotsi", "party": "ODM"},
        {"county": "Bungoma", "name": "Moses Wetang’ula", "party": "FORD-Kenya"},
        {"county": "Busia", "name": "Okiya Omtatah", "party": "NRA"},
        {"county": "Siaya", "name": "Oburu Odinga", "party": "ODM"},
        {"county": "Kisumu", "name": "Tom Ojienda", "party": "ODM"},
        {"county": "Homa Bay", "name": "Moses Kajwang’", "party": "ODM"},
        {"county": "Migori", "name": "Eddy Oketch", "party": "ODM"},
        {"county": "Kisii", "name": "Richard Onyonka", "party": "ODM"},
        {"county": "Nyamira", "name": "Okong'o Omogeni", "party": "ODM"},
        {"county": "Nairobi City", "name": "Edwin Sifuna", "party": "ODM"},
    ]

    objs = []
    for s in senators:
        try:
            county_obj = County.objects.get(name__iexact=s["county"])
            objs.append(Leader(
                name=s["name"],
                party=s["party"],
                position=senator_position,
                county=county_obj
            ))
        except County.DoesNotExist:
            print(f"County {s['county']} not found in DB, skipping...")

    Leader.objects.bulk_create(objs, ignore_conflicts=True)

def unseed_senators(apps, schema_editor):
    Leader = apps.get_model("kyl", "Leader")
    Leader.objects.filter(position__name="Senator").delete()

class Migration(migrations.Migration):

    dependencies = [
        ("kyl", "0002_seed_counties"),
    ]

    operations = [
        migrations.RunPython(seed_senators, reverse_code=unseed_senators),
    ]


