# Generated by Django 5.2.1 on 2025-08-21 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyl', '0002_auto_20250821_2135'),
        ('kyl', '0003_auto_20250821_2251'),
    ]

    operations = [
    ]
