# Generated by Django 5.2.1 on 2025-09-07 17:20

from django.db import migrations

def seed_deputy_governors(apps, schema_editor):
    Leader = apps.get_model("kyl", "Leader")
    County = apps.get_model("kyl", "County")
    Position = apps.get_model("kyl", "Position")

    # Ensure "Deputy Governor" position exists
    deputy_position, _ = Position.objects.get_or_create(name="Deputy Governor")

    deputies = [
        {"county": "Mombasa", "name": "Francis Thoya Foleni", "party": None},
        {"county": "Kwale", "name": "Josphat Chirema Kombo", "party": None},
        {"county": "Kilifi", "name": "Flora Mbetsa Chibule", "party": None},
        {"county": "Tana River", "name": "Mahadh Ali Loka", "party": None},
        {"county": "Lamu", "name": "Raphael Munyua Ndung’u", "party": None},
        {"county": "Taita–Taveta", "name": "Christine Saru Kilalo", "party": None},
        {"county": "Garissa", "name": "Abdi Dagane Muhumed", "party": None},
        {"county": "Wajir", "name": "Ahmed Muhumed Abdi", "party": None},
        {"county": "Mandera", "name": "Ali Maalim Mohamud", "party": None},
        {"county": "Marsabit", "name": "Solomon Gubo Riwe", "party": None},
        {"county": "Isiolo", "name": "Dr. James Lowasa", "party": None},
        {"county": "Meru", "name": "Mutuma Isaac M’ethingia", "party": None},
        {"county": "Tharaka Nithi", "name": "Muisrael Nyagah Derebia", "party": None},
        {"county": "Embu", "name": "Justus Kinyua Mugo", "party": None},
        {"county": "Kitui", "name": "Augustine Wambua Kanani", "party": None},
        {"county": "Machakos", "name": "Francis Mwangangi", "party": None},
        {"county": "Makueni", "name": "Lucy Mulili", "party": None},
        {"county": "Nyandarua", "name": "John Mathara Mwangi", "party": None},
        {"county": "Nyeri", "name": "David Kinaniri Waroe Mwangi", "party": None},
        {"county": "Kirinyaga", "name": "David Githanda Wachira", "party": None},
        {"county": "Murang’a", "name": "Stephen Mburu Munania", "party": None},
        {"county": "Kiambu", "name": "Rosemary Njeri Kirika", "party": None},
        {"county": "Turkana", "name": "John Erus Lopeyok", "party": None},
        {"county": "West Pokot", "name": "Robert Achaule Komole", "party": None},
        {"county": "Samburu", "name": "Gabriel Samia Lenengwesi", "party": None},
        {"county": "Trans Nzoia", "name": "Philomenah Bineah", "party": None},
        {"county": "Uasin Gishu", "name": "John Barorot", "party": None},
        {"county": "Elgeyo Marakwet", "name": "Grace Jerutich Cheserek", "party": None},
        {"county": "Nandi", "name": "Yulita Mitei Chebotip", "party": None},
        {"county": "Baringo", "name": "Charles Kipng’ok (Kipngok)", "party": None},
        {"county": "Laikipia", "name": "Reuben Kamuri Ngatia", "party": None},
        {"county": "Nakuru", "name": "David Kones", "party": None},
        {"county": "Narok", "name": "Kiprono Koech Tamalinye", "party": None},
        {"county": "Kajiado", "name": "Martin Moshisho", "party": None},
        {"county": "Kericho", "name": "Fredrick Kipng’etich Kirui", "party": None},
        {"county": "Bomet", "name": "David Shadrack Rotich", "party": None},
        {"county": "Kakamega", "name": "Ayub Savula", "party": None},
        {"county": "Vihiga", "name": "Wilberforce Kitiezo Gwadoya", "party": None},
        {"county": "Bungoma", "name": "Janepher Chemtai Mbatiany", "party": None},
        {"county": "Busia", "name": "Arthur Odera", "party": None},
        {"county": "Siaya", "name": "William Odhiambo Oduol", "party": None},
        {"county": "Kisumu", "name": "Mathew Ochieng Owili", "party": None},
        {"county": "Homa Bay", "name": "Joseph Oyugi Magwanga", "party": None},
        {"county": "Migori", "name": "Joseph Gimunta Mahiri", "party": None},
        {"county": "Kisii", "name": "Robert Onsare Monda", "party": None},
        {"county": "Nyamira", "name": "James Ondicho Gesami", "party": None},
        {"county": "Nairobi City", "name": "James Njoroge Muchiri", "party": None},
    ]

    objs = []
    for d in deputies:
        try:
            county = County.objects.get(name__iexact=d["county"])
            objs.append(Leader(
                name=d["name"],
                party=d["party"],
                position=deputy_position,
                county=county
            ))
        except County.DoesNotExist:
            print(f"County {d['county']} not found in DB, skipping...")

    Leader.objects.bulk_create(objs, ignore_conflicts=True)


def unseed_deputy_governors(apps, schema_editor):
    Leader = apps.get_model("kyl", "Leader")
    Leader.objects.filter(position__name="Deputy Governor").delete()




class Migration(migrations.Migration):

    dependencies = [
        ('kyl', '0003_senators'),
    ]

    operations = [
        migrations.RunPython(seed_deputy_governors, reverse_code=unseed_deputy_governors),
    ]
