# Generated by Django 5.2.1 on 2025-09-07 17:44

from django.db import migrations

def seed_governors(apps, schema_editor):
    Leader = apps.get_model("kyl", "Leader")
    County = apps.get_model("kyl", "County")
    Position = apps.get_model("kyl", "Position")

    position, _ = Position.objects.get_or_create(name="Governor")

    governors = [
        {"county": "Mombasa", "name": "Abdullswamad Nassir", "party": "ODM"},
        {"county": "Kwale", "name": "Fatuma Achani", "party": "UDA"},
        {"county": "Kilifi", "name": "Gideon Mung’aro", "party": "ODM"},
        {"county": "Tana River", "name": "Dhadho Godhana", "party": "ODM"},
        {"county": "Lamu", "name": "Issa Timamy", "party": "ANC"},
        {"county": "Taita–Taveta", "name": "Andrew Mwadime", "party": "Independent"},
        {"county": "Garissa", "name": "Nathif Jama", "party": "ODM"},
        {"county": "Wajir", "name": "Ahmed Abdullahi", "party": "ODM"},
        {"county": "Mandera", "name": "Mohamed Khalif", "party": "ODM"},
        {"county": "Marsabit", "name": "Mohamud Ali", "party": "UDA"},
        {"county": "Isiolo", "name": "Abdi Guyo", "party": "JP"},
        {"county": "Meru", "name": "Kawira Mwangaza", "party": "Independent"},
        {"county": "Tharaka Nithi", "name": "Muthomi Njuki", "party": "UDA"},
        {"county": "Embu", "name": "Cecily Mbarire", "party": "UDA"},
        {"county": "Kitui", "name": "Julius Malombe", "party": "Wiper"},
        {"county": "Machakos", "name": "Wavinya Ndeti", "party": "Wiper"},
        {"county": "Makueni", "name": "Mutula Kilonzo Jr", "party": "Wiper"},
        {"county": "Nyandarua", "name": "Kiarie Badilisha", "party": "UDA"},
        {"county": "Nyeri", "name": "Mutahi Kahiga", "party": "UDA"},
        {"county": "Kirinyaga", "name": "Anne Waiguru", "party": "UDA"},
        {"county": "Murang’a", "name": "Irungu Kang’ata", "party": "UDA"},
        {"county": "Kiambu", "name": "Kimani Wamatangi", "party": "UDA"},
        {"county": "Turkana", "name": "Jeremiah Lomorukai", "party": "ODM"},
        {"county": "West Pokot", "name": "Simon Kachapin", "party": "UDA"},
        {"county": "Samburu", "name": "Lati Lelelit", "party": "UDA"},
        {"county": "Trans Nzoia", "name": "George Natembeya", "party": "DAP-K"},
        {"county": "Uasin Gishu", "name": "Jonathan Bii", "party": "UDA"},
        {"county": "Elgeyo Marakwet", "name": "Wesley Rotich", "party": "UDA"},
        {"county": "Nandi", "name": "Stephen Sang", "party": "UDA"},
        {"county": "Baringo", "name": "Benjamin Cheboi", "party": "UDA"},
        {"county": "Laikipia", "name": "Joshua Irungu", "party": "UDA"},
        {"county": "Nakuru", "name": "Susan Kihika", "party": "UDA"},
        {"county": "Narok", "name": "Patrick Ole Ntutu", "party": "UDA"},
        {"county": "Kajiado", "name": "Joseph Ole Lenku", "party": "ODM"},
        {"county": "Kericho", "name": "Eric Mutai", "party": "UDA"},
        {"county": "Bomet", "name": "Hillary Barchok", "party": "UDA"},
        {"county": "Kakamega", "name": "Fernandes Barasa", "party": "ODM"},
        {"county": "Vihiga", "name": "Wilber Ottichilo", "party": "ODM"},
        {"county": "Bungoma", "name": "Kenneth Lusaka", "party": "FORD-Kenya"},
        {"county": "Busia", "name": "Paul Otuoma", "party": "ODM"},
        {"county": "Siaya", "name": "James Orengo", "party": "ODM"},
        {"county": "Kisumu", "name": "Anyang’ Nyong’o", "party": "ODM"},
        {"county": "Homa Bay", "name": "Gladys Wanga", "party": "ODM"},
        {"county": "Migori", "name": "Ochillo Ayacko", "party": "ODM"},
        {"county": "Kisii", "name": "Simba Arati", "party": "ODM"},
        {"county": "Nyamira", "name": "Amos Nyaribo", "party": "UPA"},
        {"county": "Nairobi City", "name": "Johnson Sakaja", "party": "UDA"},
    ]

    objs = []
    for g in governors:
        try:
            county = County.objects.get(name__iexact=g["county"])
            objs.append(Leader(
                name=g["name"],
                party=g["party"],
                position=position,
                county=county
            ))
        except County.DoesNotExist:
            print(f"County {g['county']} not found in DB, skipping...")

    Leader.objects.bulk_create(objs, ignore_conflicts=True)

def unseed_governors(apps, schema_editor):
    Leader = apps.get_model("kyl", "Leader")
    Leader.objects.filter(position__name="Governor").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('kyl', '0005_women'),
    ]

    operations = [
        migrations.RunPython(seed_governors, reverse_code=unseed_governors),
    ]
