# Generated by Django 5.2.1 on 2025-08-21 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyl', '0005_auto_20250821_2308'),
        ('kyl', '0006_auto_20250821_2314'),
    ]

    operations = [
    ]
