# Generated by Django 5.2.1 on 2025-08-21 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyl', '0007_merge_0005_auto_20250821_2308_0006_auto_20250821_2314'),
        ('kyl', '0008_auto_20250821_2327'),
    ]

    operations = [
    ]
