# Generated by Django 5.2.1 on 2025-08-23 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyl', '0009_merge_20250821_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='kyl.position')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
