# Generated by Django 5.2.1 on 2025-08-23 07:48
from django.db import migrations

def seed_deputy_president_roles(apps, schema_editor):
    Position = apps.get_model("kyl", "Position")
    Role = apps.get_model("kyl", "Role")

    # Ensure Deputy President position exists
    deputy_president, _ = Position.objects.get_or_create(name="Deputy President")

    # Define roles
    roles = [
        {
            "title": "Assist the President",
            "description": "Supports the President in executing government functions and national leadership."
        },
        {
            "title": "Act as President",
            "description": "Assumes presidential duties when the President is absent, incapacitated, or otherwise unable to serve."
        },
        {
            "title": "Cabinet Oversight",
            "description": "Oversees performance of ministries as directed by the President."
        },
        {
            "title": "Policy Coordination",
            "description": "Coordinates government policies across ministries and departments."
        },
        {
            "title": "Public Representation",
            "description": "Represents the government in national and international functions when delegated by the President."
        },
    ]

    # Create roles
    for role in roles:
        Role.objects.get_or_create(
            position=deputy_president,
            title=role["title"],
            defaults={"description": role["description"]}
        )




class Migration(migrations.Migration):

    dependencies = [
        ('kyl', '0011_alter_position_name'),
    ]

    operations = [
        migrations.RunPython(seed_deputy_president_roles),
    ]
