# Generated by Django 5.2.1 on 2025-08-28 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyl', '0019_women_rep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('location_type', models.CharField(choices=[('ward', 'Ward'), ('constituency', 'Constituency'), ('county', 'County')], max_length=20)),
                ('position', models.CharField(choices=[('governor', 'Governor'), ('senator', 'Senator'), ('mp', 'Member of Parliament'), ('women_rep', 'Women Representative'), ('mca', 'MCA')], max_length=20)),
                ('election_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('party', models.CharField(max_length=100)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='kyl.election')),
            ],
        ),
    ]
