# Generated by Django 5.2.1 on 2025-09-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyl', '0020_election_candidate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='constituency',
            options={'verbose_name_plural': 'Constituencies'},
        ),
    ]
